@commandon = switch3 on
@commandoff = switch3 off

### GET Working ON
GET http://192.168.100.200:8090/switch2 on?

### GET Working OFF
GET http://192.168.100.200:8090/switch2 off?


### POST Working ON
POST http://192.168.100.200:8090/{{commandon}}?

### POST Working OFF
POST http://192.168.100.200:8090/{{commandoff}}?
